version: '3.7'

services:
  db:
    image: postgres:16.2
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ~/Documentos/volumes/boostingdevs:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: sample
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  pgdata:
